### ISSUE TITLE
URL Resolution fails randomly

### ISSUE THREAD

**Issue by kurisubrooks** [kurisubrooks/glass2#12]
Some websites completely fail URL resolution and fallback to searching with google, whereas some other domains resolve correctly. 

Example of a working domain: `youtube.com`
Example of a failing domain: `kurisubrooks.com`

**Comment by justin97530** [comment]
Fixed with 58bcecf

**Comment by craigmc08** [comment]
https://github.com/kurisubrooks/glass2/commit/58bcecfe210ed8d27137a8fdd7d5d56389fc7ec7 does not fix this issue, and causes the url bar to fail in every case.

**Comment by craigmc08** [comment]
4bb079c81e15b6abb2ea8b43605540b60f9ca323 fixes this by removing char 13 at the end of each TLD entry.

**Comment by justin97530** [comment]
@craigmc08 4bb079c causes the last character of the TLD to be removed (at least on macOS High Sierra).

This causes the TLDs to miss one character, such as the following:
AUCTION -> AUCTIO
COM -> CO
CO -> C
ME -> M
NET -> NE

Using the commit, when I type "google.com" into the URL bar, it searches for the domain instead, and logging `this.tlds` shows the above. ![image](https://user-images.githubusercontent.com/2884155/31861786-87016ecc-b750-11e7-90c7-bcfdbe890c86.png)

**Comment by craigmc08** [comment]
Could this be an OS specific thing. Windows uses different end of line characters, right? What OS are you using?

**Comment by justin97530** [comment]
Yeah that's definitely possible, it could be that the TLD file is using a Linux-style newline. I'm on macOS 10.13.

**Comment by justin97530** [comment]
Could you test if 12d23ee fixes this issue?

**Comment by craigmc08** [comment]
The line ending issue is fixed by that (at least on Windows). Your urlRegex does have a problem though. It does not recognize TLDs such as .google, .rocks, or .xn--ogbpf8fl. I believe 342637a5eee235a6350c623d01896709891e33b6 fixes this. The maximum allowed length for a tld is 63 (https://tools.ietf.org/id/draft-liman-tld-names-01.html)

**Comment by justin97530** [comment]
I didn't notice that, thanks for the fix. 12d23ee works on macOS as well. If the issue is resolved, I'll close this and merge into master.
